FROM rocker/rstudio:4.1.2

USER root

WORKDIR /home/rstudio

#install some base libs
RUN apt-get update && \
	apt-get -y --no-install-recommends install --fix-missing \
        apt-file \
        apt-utils \
        build-essential \
        bzip2 \
        ca-certificates \
        cmake \
        curl \
	default-jdk \
        default-jre\
        gdb \
        git \
        hdf5-helpers \
        lbzip2 \
        libbz2-dev \
        libcairo2-dev \
        libcurl4-openssl-dev \
        libfftw3-dev \
        libgeos-dev \
        libgl1-mesa-dev \
        libglpk-dev \
        libglu1-mesa-dev \
        libgsl0-dev \
        libhdf4-alt-dev \
        libhdf5-dev \
        libjpeg-dev \
        libjq-dev \
        liblzma-dev \
        libmariadbd-dev \
        libnetcdf-dev \
        libpng-dev \
        libpq-dev \
        libproj-dev \
        libprotobuf-dev \
        libsqlite3-dev \
        libssh2-1-dev \
        libssl-dev \
        libudunits2-dev \
        libxml2-dev \
        libxt-dev \
        libz-dev \
        make \
        netcdf-bin \
        postgis \
        protobuf-compiler \
        python3-dev \
        python3-pip \
        sqlite3 \
        tk-dev \
        unixodbc-dev \
        unzip \
        vim \
        libpoppler-cpp-dev \
        samtools \
        bedtools \
        subread \
        libpicard-java \
        igv \
        fastqc \
        trimmomatic \
        unzip \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

# FFTW, FIt-SNE
RUN wget http://www.fftw.org/fftw-3.3.8.tar.gz \
    && tar zxvf fftw-3.3.8.tar.gz \
    && rm fftw-3.3.8.tar.gz \
    && cd fftw-3.3.8 \
    && ./configure \
    && make \
    && make install \
    && git clone https://github.com/KlugerLab/FIt-SNE.git \
    && cd FIt-SNE/ \
    && g++ -std=c++11 -O3  src/sptree.cpp src/tsne.cpp src/nbodyfft.cpp  -o bin/fast_tsne -pthread -lfftw3 -lm \
    && cp bin/fast_tsne /usr/local/bin/

# Install R packages
RUN R -e "install.packages('BiocManager', dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('devtools', dependencies=TRUE, repos='http://cran.rstudio.com/')"

COPY ./packages.R /home/rstudio

RUN Rscript /home/rstudio/packages.R
RUN pip3 install CITE-seq-Count==1.4.5

RUN R -e "devtools::install_github('satijalab/seurat-wrappers')"

#SRAtoolkit
RUN wget http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.11.3/sratoolkit.2.11.3-ubuntu64.tar.gz \
    && tar zxvf sratoolkit.2.11.3-ubuntu64.tar.gz

#scTE
RUN git clone https://github.com/JiekaiLab/scTE.git \
    && cd scTE \
    && git checkout 6d1b84068a958e80a0062d45b497522cf4f860b1 \
    && python3 setup.py install

RUN wget -O cellranger-6.1.2.tar.gz "https://cf.10xgenomics.com/releases/cell-exp/cellranger-6.1.2.tar.gz?Expires=1641869001&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZi4xMHhnZW5vbWljcy5jb20vcmVsZWFzZXMvY2VsbC1leHAvY2VsbHJhbmdlci02LjEuMi50YXIuZ3oiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDE4NjkwMDF9fX1dfQ__&Signature=d4beB8Lg4Ie7sd4otu6lAR1N4mG0~Uf8LtajH7Xs8hfB-hsyWbklpKKln5U8vmHHdPXRXVNr9UfeH7OBXCkRFlIWZFrkmfUffsvez~KCCyjF8K1BUb-fJ9WKFogyeLfY0WPTHhQYEeOUAoToe60Yi7teSo7tDkkBKl3M~44RXQAUmW5ATtDwrAL-goyJPwR11ZYU~PZOUQj8Kv6otk4Ra7Rx035bHPhgdN7kSbHuS~yTc~GnyjL79B~zeWtrE7Fn4ZqFuDdbjSuUOpGV-bZdX56cWsM~aQYHIo2-B3gGcynapwm2lLVDvVuGM0kcHoQKZ6ck7X28Ra9l~IT82acCWg__&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA" \
    && tar zxvf cellranger-6.1.2.tar.gz

#STAR
RUN wget https://github.com/alexdobin/STAR/archive/2.7.9a.tar.gz \
    && tar -xzf 2.7.9a.tar.gz \
    && cd STAR-2.7.9a/source \
    && make STAR

